### ISSUE TITLE
Add per-entry compression

### ISSUE THREAD

**Issue by eeucalyptus** [phoboslab/qop#1]
Rn the format suffers from the old tarball problem that you can't compress the contents of the individual entries without having to deal with a custom compression layer

**Comment by phoboslab** [comment]
Adding some form of compression into QOP directly will increase complexity quite a bit. That's not something I want to do.

What about a `.flags` field to `qop_file`? QOP could come with some defined (e.g. `QOP_FLAG_ZSTD`, `QOP_FLAG_DEFLATE`, extensible by the client), but decompression would still need to be handled by the client.

**Comment by GithubPrankster** [comment]
Per-entry would be nice to selectively handle certain file formats like video/audio which tend to not play well with being losslessly compressed on top of the existing data, but I believe most compression algorithms have a "write next i bytes" opcode that should be sufficient for an encoder to have certain formats be basically written uncompressed.
EDIT: Though having everything be compressed in some way would make it impossible to seek through a file inside the compression enabled qop without first decompressing it to memory.
