### ISSUE TITLE
Add file paths to index

### ISSUE THREAD

**Issue by GithubPrankster** [phoboslab/qop#2]
The format is very concise and would be wonderful as an alternative to zip/7z for my game engine, but lack of paths makes it difficult for the usecase I'm currently exploring of implementing an "install wizard" program. I also want players to be able to unpack the files no problem to access and even modify them.

The current hash-based method is ideal for finding and getting a hold of a file but it has no other info about what it was. QOP definitely does not seem to aim to be like the toughest (and sometimes [hilariously complex](https://blog.cmpxchg8b.com/2012/09/fun-with-constrained-programming.html)) archival formats out there but a simple `size+data` (I bet the size can be confidently just a `u16`) would place it on par with a format like Godot Engine's [PCK](https://github.com/godotengine/godot/blob/master/core/io/pck_packer.cpp).

**Comment by bullno1** [comment]
The format can be like this:

```c
struct {
	// Data of all files in this archive
	uint8_t file_data[];
        // Name data
        uint8_t file_names[];

	// The index, with a list of files
	struct {
		uint64_t hash;
		uint32_t data_offset;
		uint32_t data_size;
                uint32_t name_offset;
                uint32_t name_len;
	} qop_file[];

	// Beginning of the archive from file end
	uint32_t files_offset; 

	// The length of the index in `1 << index_bits`
	uint32_t index_bits;

	// Magic bytes "qopf"
	uint32_t magic;
} qop;
```

Basically, name will be another chunk after data.
Should it be read as part of the index though?

**Comment by phoboslab** [comment]
I agree, having the full path in the archive is a good idea.

`qop_file.offset` could point to the beginning of the string, a new field `qop_file.path_len` would denote the length of the path string and file data starts immediately after. No need for separate `.data_offset` and `.path_offset`!? This layout would also help when looking at the archive in a hex editor: each file is prefixed with its path.

E.g.:
```
struct {
	uint64_t hash;
	uint32_t offset;
	uint16_t flags; // See issue #1
	uint16_t path_size;
	uint32_t data_size;
} qop_file[];
```

Didn't know about Godot's PCK; I'll look into it. Maybe there's some more ideas we could steal :)
