### ISSUE TITLE
Storing the hash seed

### ISSUE THREAD

**Issue by bullno1** [phoboslab/qop#3]
While this is unlikely, 64bit hash can have collision. But it is possible to find a seed where the set of names do not collide on. Usually, it's just incrementing the current seed and hash everything again. Most of the time there wouldn't be any collision, on the off chance there is, the second iteration should take care of it.

Should the hash be seeded and the seed be stored in the header?

**Comment by phoboslab** [comment]
64bit _should_ provide enough space to not collide with even a few million of files. If that's actually the case remains to be tested. For QOPs use-case it doesn't need to be protected against adversarial attacks, so my hunch is that it's “good enough”.

If there are trivial collisions, storing the seed may not be a bad idea. But we could also just make the hash map check the (now stored) path on lookup!? In any case, I don't want to implement either of these until we know it's necessary.

**Comment by bullno1** [comment]
You're right, I ran `find ~ > /tmp/list` and hash all of them, about 1.2mil files in my home dir and not a single collision.
