### ISSUE TITLE
[enhancement] offset from the end?

### ISSUE THREAD

**Issue by ListeriaM** [phoboslab/qop#6]
Would you consider storing `files_offset` as an offset from the end of the file?  
This way any package can be appended to any file, regardless of the size of the file.

**Comment by ListeriaM** [comment]
Thinking about this some more, if the files grow down starting from the index, you don't need to store the `files_offset` field in the header (it's just `-QOP_HEADER_SIZE - index_len*QOP_INDEX_SIZE`), though I'm not sure saving 4 bytes is worth the hassle.

**Comment by phoboslab** [comment]
There's a bit of a naming problem here. The `files_offset` stored in the archive is the offset of the very first file (actually the very first path) from the _end_ of the archive. I.e. `files_offset` is the size of the whole archive, including the header. Maybe renaming it to `archive_size` would make this a bit clearer!?

The `files_offset` that gets stored in the `qop_desc` is then [computed](https://github.com/phoboslab/qop/blob/master/qop.h#L188) as the offset from the beginning of the whole file (`size - qop_read_32(fh);`), so we can easy `fseek()` to it. For a standalone `archive.qop`, the `qop_desc.files_offset` will be `0`.

The `qop_file.offset` is the offset for that file from the _beginning_ of the archive.

Maybe I am misunderstanding the issue!? In any case, the current situation is quite confusing; I'll clear this up.

**Comment by phoboslab** [comment]
Renamed to `archive_size` in the file format description in https://github.com/phoboslab/qop/commit/e35e46ad801f950a201629c0a0fef73e7f6dfcde

**Comment by ListeriaM** [comment]
> Maybe I am misunderstanding the issue!? In any case, the current situation is quite confusing; I'll clear this up.

you're not, I was just confused by the name, thanks for clearing it up.
