### ISSUE TITLE
`qop_open()` does not correctly guard against incorrect magic/index length

### ISSUE THREAD

**Issue by GithubPrankster** [phoboslab/qop#7]
https://github.com/phoboslab/qop/blob/bc4664cdf8f3c0594e7a5e1180e4faeb000ad5ed/qop.h#L198-L201

Attempting to run this on a executable where the usecase was to attempt opening itself as an QOP before falling back to opening normal directories made it mysteriously fallthrough and get stuck in the hashmap length loop. I am still not quite able to tell how this can be fixed.

**Comment by phoboslab** [comment]
That was quite silly. Thanks for reporting!
